ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS category      VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS program       VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS professor     VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reviewer_name VARCHAR(100) NOT NULL DEFAULT '';
